In [55]:
import pandas as pd
import plotly.graph_objects as go

In [61]:
aps = pd.read_csv("output/ap_positions.csv")
aps

,id,type,x_pdf_pt,y_pdf_pt,x_px,y_px,bbox_pdf_pt,cluster_items
0,AP_001,violet,504.051,237.193,2100.2,988.3,"[503.502, 236.654, 504.601, 237.733]",16
1,AP_002,violet,394.804,237.214,1645.0,988.4,"[394.264, 236.674, 395.344, 237.754]",16
2,AP_003,violet,619.176,237.233,2579.9,988.5,"[618.636, 236.694, 619.716, 237.773]",16
3,AP_004,violet,722.655,237.353,3011.1,989.0,"[722.115, 236.814, 723.195, 237.893]",16
4,AP_005,orange,511.919,237.374,2133.0,989.1,"[511.379, 236.834, 512.458, 237.913]",16
5,AP_006,orange,607.061,237.413,2529.4,989.2,"[606.521, 236.874, 607.6, 237.953]",16
6,AP_007,orange,734.690,237.413,3061.2,989.2,"[734.151, 236.874, 735.23, 237.953]",16
7,AP_008,violet,231.149,237.453,963.1,989.4,"[230.609, 236.914, 231.689, 237.993]",16
8,AP_009,orange,397.354,237.473,1655.6,989.5,"[396.804, 236.934, 397.903, 238.013]",16
9,AP_010,violet,640.018,237.483,2666.7,989.5,"[639.468, 236.934, 640.568, 238.033]",16
10,AP_011,orange,709.040,237.493,2954.3,989.6,"[708.501, 236.954, 709.58, 238.033]",16
11,AP_012,orange,351.242,237.514,1463.5,989.6,"[350.702, 236.974, 351.781, 238.053]",16
12,AP_013,violet,450.313,237.553,1876.3,989.8,"[449.763, 237.014, 450.863, 238.093]",16
13,AP_014,orange,626.404,237.573,2610.0,989.9,"[625.854, 237.034, 626.953, 238.113]",16
14,AP_015,violet,530.211,237.613,2209.2,990.1,"[529.671, 237.073, 530.751, 238.153]",16
15,AP_016,orange,284.008,237.684,1183.4,990.3,"[283.468, 237.134, 284.548, 238.233]",16
16,AP_017,orange,265.735,237.693,1107.2,990.4,"[265.195, 237.154, 266.275, 238.233]",16
17,AP_018,orange,442.216,237.693,1842.6,990.4,"[441.666, 237.154, 442.766, 238.233]",16
18,AP_019,violet,278.170,237.713,1159.0,990.5,"[277.63, 237.173, 278.71, 238.253]",16
19,AP_020,orange,492.266,237.773,2051.1,990.7,"[491.726, 237.234, 492.806, 238.313]",16
20,AP_021,orange,216.075,237.813,900.3,990.9,"[215.535, 237.273, 216.614, 238.353]",16
21,AP_022,violet,303.151,237.813,1263.1,990.9,"[302.601, 237.273, 303.7, 238.353]",16
22,AP_023,violet,346.944,237.874,1445.6,991.1,"[346.404, 237.334, 347.483, 238.413]",16
23,AP_024,orange,235.027,237.953,979.3,991.5,"[234.488, 237.414, 235.567, 238.493]",16
24,AP_025,violet,172.072,237.993,717.0,991.6,"[171.532, 237.454, 172.612, 238.533]",16
25,AP_026,orange,175.581,238.053,731.6,991.9,"[175.031, 237.513, 176.13, 238.593]",16
26,AP_027,violet,206.329,238.193,859.7,992.5,"[205.779, 237.654, 206.879, 238.733]",16
27,AP_028,orange,161.197,238.993,671.7,995.8,"[160.657, 238.453, 161.736, 239.533]",16
28,AP_029,orange,325.072,239.092,1354.5,996.2,"[324.532, 238.553, 325.612, 239.632]",16
29,AP_030,violet,159.817,239.692,665.9,998.7,"[159.277, 239.153, 160.357, 240.232]",16
30,AP_031,violet,736.010,240.152,3066.7,1000.6,"[735.47, 239.612, 736.55, 240.692]",16
31,AP_032,orange,147.902,250.008,616.3,1041.7,"[147.362, 249.469, 148.441, 250.548]",16
32,AP_033,violet,735.061,257.326,3062.8,1072.2,"[734.511, 256.786, 735.61, 257.865]",16
33,AP_034,violet,132.248,266.402,551.0,1110.0,"[131.708, 265.862, 132.788, 266.942]",16
34,AP_035,orange,42.573,268.301,177.4,1117.9,"[42.023, 267.761, 43.123, 268.841]",16
35,AP_036,orange,42.763,272.060,178.2,1133.6,"[42.223, 271.52, 43.303, 272.6]",16
36,AP_037,orange,124.021,273.739,516.8,1140.6,"[123.471, 273.199, 124.571, 274.279]",16
37,AP_038,orange,733.661,274.209,3056.9,1142.5,"[733.111, 273.659, 734.211, 274.759]",16
38,AP_039,violet,120.003,277.618,500.0,1156.7,"[119.453, 277.078, 120.552, 278.157]",16
39,AP_040,violet,99.561,278.837,414.8,1161.8,"[99.021, 278.297, 100.1, 279.377]",16
40,AP_041,orange,93.303,280.296,388.8,1167.9,"[92.763, 279.757, 93.843, 280.836]",16
41,AP_042,orange,112.476,280.776,468.7,1169.9,"[111.936, 280.237, 113.016, 281.316]",16
42,AP_043,orange,75.070,285.915,312.8,1191.3,"[74.531, 285.375, 75.61, 286.454]",16
43,AP_044,violet,73.491,286.274,306.2,1192.8,"[72.951, 285.734, 74.031, 286.814]",16
44,AP_045,orange,42.893,287.714,178.7,1198.8,"[42.343, 287.174, 43.443, 288.254]",16
45,AP_046,orange,64.145,288.173,267.3,1200.7,"[63.595, 287.634, 64.695, 288.713]",16
46,AP_047,violet,63.035,288.193,262.6,1200.8,"[62.495, 287.654, 63.575, 288.733]",16
47,AP_048,violet,722.195,298.589,3009.1,1244.1,"[721.655, 298.05, 722.735, 299.129]",16
48,AP_049,violet,748.045,300.189,3116.9,1250.8,"[747.505, 299.649, 748.585, 300.729]",16
49,AP_050,violet,735.770,301.769,3065.7,1257.4,"[735.23, 301.229, 736.31, 302.308]",16
50,AP_051,orange,42.503,309.825,177.1,1290.9,"[41.963, 309.285, 43.043, 310.365]",16
51,AP_052,orange,42.513,312.324,177.1,1301.3,"[41.963, 311.784, 43.063, 312.864]",16
52,AP_053,violet,733.741,321.540,3057.3,1339.7,"[733.191, 321.0, 734.291, 322.08]",16
53,AP_054,violet,735.121,322.440,3063.0,1343.5,"[734.571, 321.9, 735.67, 322.98]",16
54,AP_055,orange,43.133,324.699,179.7,1352.9,"[42.483, 323.539, 43.783, 325.859]",32

In [62]:
traj = pd.read_csv("output/wall_curves.csv")
traj

,curve_id,vertex_index,x_pdf_pt,y_pdf_pt,x_px,y_px,curve_length_pdf_pt,curve_length_px
0,WC_0001,0,792.72,204.24,3303.0,851.0,147.530,614.7
1,WC_0001,1,792.24,212.40,3301.0,885.0,147.530,614.7
2,WC_0001,2,795.60,213.12,3315.0,888.0,147.530,614.7
3,WC_0001,3,796.80,214.56,3320.0,894.0,147.530,614.7
4,WC_0001,4,792.24,216.48,3301.0,902.0,147.530,614.7
...,...,...,...,...,...,...,...,...
947,WC_0129,4,800.16,336.00,3334.0,1400.0,36.317,151.3
948,WC_0129,5,801.84,336.00,3341.0,1400.0,36.317,151.3
949,WC_0129,6,802.80,335.04,3345.0,1396.0,36.317,151.3
950,WC_0129,7,802.80,331.68,3345.0,1382.0,36.317,151.3
951,WC_0129,8,804.48,330.72,3352.0,1378.0,36.317,151.3

In [63]:
traj.columns

Index(['curve_id', 'vertex_index', 'x_pdf_pt', 'y_pdf_pt', 'x_px', 'y_px',
       'curve_length_pdf_pt', 'curve_length_px'],
      dtype='object')

In [64]:
aps.columns

Index(['id', 'type', 'x_pdf_pt', 'y_pdf_pt', 'x_px', 'y_px', 'bbox_pdf_pt',
       'cluster_items'],
      dtype='object')

In [65]:
fig = go.Figure()


for idx in traj['curve_id'].unique():
    subset = traj.loc[traj['curve_id'] == idx]
    fig.add_trace(
        go.Scatter(
            x = subset['x_pdf_pt'],
            y = subset['y_pdf_pt'],
            mode='markers + lines',
            marker=dict({"color" : "black"}),
            showlegend=False
        ),
    )

violet_aps = aps[aps['type'] == 'violet']
for ap_id in violet_aps['id'].unique():
    subset = violet_aps.loc[violet_aps['id'] == ap_id]
    fig.add_trace(
        go.Scatter(
            x = subset['x_pdf_pt'],
            y = subset['y_pdf_pt'],
            mode='markers',
            marker=dict(
                size=8,
                color='rgba(0, 0, 0, 0)',
                line=dict(
                    color='blueviolet',
                    width=2
                )),
            name=str(ap_id)
        ),

    )

orange_aps = aps[aps['type'] == 'orange']
for ap_id in orange_aps['id'].unique():
    subset = orange_aps.loc[orange_aps['id'] == ap_id]
    fig.add_trace(
        go.Scatter(
            x = subset['x_pdf_pt'],
            y = subset['y_pdf_pt'],
            mode='markers',
            marker=dict(
                size=8,
                color='rgba(0, 0, 0, 0)',
                line=dict(
                    color='orange',
                    width=2
                )),
            name=str(ap_id)
        ),

    )

fig.update_layout(
    yaxis=dict(
        autorange='reversed',
        scaleanchor='x',  # Locks the y-scale to the x-scale
        scaleratio=1      # Sets the aspect ratio to 1:1
    )
)
fig.update_layout(width=1500, height=800)
fig.show()